awslabs/app-server-migration

src/main/java/com/amazon/aws/am2/appmig/glassviewer/constructs/ClassConstruct.java
src/main/java/com/amazon/aws/am2/appmig/glassviewer/constructs/InterfaceConstruct.java

Changed get package method to return _default_ in case of null package name

Support classes under default package

---

src/main/resources/reporttemplate.html

Changed the text in the report from specifc servers and made it generic. 

---

LICENSE-svnkit
README.md
pom.xml
src/main/java/com/amazon/aws/am2/appmig/checkout/ConfigurationBean.java
src/main/java/com/amazon/aws/am2/appmig/checkout/IRepoManager.java
src/main/java/com/amazon/aws/am2/appmig/checkout/RepoDetails.java
src/main/java/com/amazon/aws/am2/appmig/checkout/RepoManagerFactory.java
src/main/java/com/amazon/aws/am2/appmig/checkout/RepoType.java
src/main/java/com/amazon/aws/am2/appmig/checkout/SVNRepoManager.java
src/main/java/com/amazon/aws/am2/appmig/checkout/SourceCodeManager.java
src/main/java/com/amazon/aws/am2/appmig/checkout/package-info.java
src/main/java/com/amazon/aws/am2/appmig/estimate/Main.java
src/main/java/com/amazon/aws/am2/appmig/estimate/exception/UnsupportedRepoException.java
src/main/resources/configuration.csv

Enhanced tool to be able to checkout code from SVN using the details provided in the configuration file

SVN Checkout feature added

---

README.md

README modification 
- added example
- fix typo

add helper examples to README

---

src/main/java/com/amazon/aws/am2/appmig/estimate/properties/PropertyFileAnalyzer.java
src/main/java/com/amazon/aws/am2/appmig/utils/Utility.java
src/main/resources/weblogic-to-tomcat-javarules.json
src/main/resources/weblogic-to-tomcat-properties.json

Added rule for JMS connection properties
Fixed property analyzer

Added JMS property rules

---

src/main/java/com/amazon/aws/am2/appmig/estimate/Estimator.java
src/main/java/com/amazon/aws/am2/appmig/estimate/Main.java
src/main/java/com/amazon/aws/am2/appmig/estimate/mvn/MvnEstimator.java
src/main/java/com/amazon/aws/am2/appmig/estimate/xml/XMLFileAnalyzer.java
src/main/java/com/amazon/aws/am2/appmig/utils/Utility.java
src/main/resources/weblogic-to-tomcat-xml.json

added xml support

---

src/main/java/com/amazon/aws/am2/appmig/estimate/Main.java
src/main/java/com/amazon/aws/am2/appmig/estimate/ProjectEstimator.java

findAllProjectsSources defined in Main and ProjectEstimator refactored

findAllProjectsSources defined in Main and ProjectEstimator refactored

---

src/main/java/com/amazon/aws/am2/appmig/estimate/Recommendation.java
src/main/java/com/amazon/aws/am2/appmig/estimate/StandardReport.java
src/main/resources/recommendations.json

add default recommendation

---

src/main/java/com/amazon/aws/am2/appmig/estimate/DefaultFilter.java
src/main/java/com/amazon/aws/am2/appmig/estimate/Estimator.java
src/main/java/com/amazon/aws/am2/appmig/estimate/Main.java

fix the scanning of child projects in parent project and Filtering of target directory during project folder scan

fix the scanning of child projects in parent project and Filtering of target directory during project folder scan

---

src/main/resources/oracle-to-postgres-javarules.json
src/main/resources/oracle-to-postgres-recommendations.json

Created initial draft of Rules and Recommendations for migration Database of Java Application from Oracle to Postgres

Rules & Recommendations for Oracle to Postgres Migration

---

src/main/java/com/amazon/aws/am2/appmig/constants/IConstants.java
src/main/java/com/amazon/aws/am2/appmig/estimate/Estimator.java
src/main/java/com/amazon/aws/am2/appmig/estimate/Main.java
src/main/java/com/amazon/aws/am2/appmig/estimate/MavenDependency.java
src/main/java/com/amazon/aws/am2/appmig/estimate/mvn/MVNBuildFileAnalyzer.java
src/main/java/com/amazon/aws/am2/appmig/estimate/mvn/MvnEstimator.java
src/main/java/com/amazon/aws/am2/appmig/glassviewer/AbstractJavaGlassViewer.java
src/main/java/com/amazon/aws/am2/appmig/glassviewer/constructs/ProjectConstruct.java
src/main/java/com/amazon/aws/am2/appmig/glassviewer/db/AppDiscoveryGraphDB.java
src/main/java/com/amazon/aws/am2/appmig/glassviewer/db/IAppDiscoveryGraphDB.java
src/main/java/com/amazon/aws/am2/appmig/glassviewer/db/QueryBuilder.java
src/main/java/com/amazon/aws/am2/appmig/utils/Utility.java
src/main/resources/log4j.properties

added features to find parent and child relationship along with dependencies

---

src/main/resources/reporttemplate.html

enhanced the text

---

src/main/java/com/amazon/aws/am2/appmig/estimate/Plan.java
src/main/java/com/amazon/aws/am2/appmig/estimate/StandardReport.java

P1-Display the line numbers for a particular file in ascending order

P1-Display the line numbers for a particular file in ascending order

---

src/main/resources/oracle-to-postgres-javarules.json
src/main/resources/oracle-to-postgres-recommendations.json

Updated rules and recommendations for Oracle to Postgres Migration

---

run.ps1
run.sh

copy lib dependencies to target/

copy lib dependencies to target/

---

README.md

added README section for rules

added README section for rules

---

src/main/java/com/amazon/aws/am2/appmig/estimate/Estimator.java
src/main/java/com/amazon/aws/am2/appmig/estimate/Main.java
src/main/java/com/amazon/aws/am2/appmig/estimate/ProjectEstimator.java
src/main/java/com/amazon/aws/am2/appmig/estimate/StandardReport.java
src/main/java/com/amazon/aws/am2/appmig/estimate/mvn/MvnEstimator.java
src/main/java/com/amazon/aws/am2/appmig/utils/RuleFileFilter.java
src/main/java/com/amazon/aws/am2/appmig/utils/Utility.java

Added functionlity to accept multiple rules files

Added functionlity to accept multiple rules files

---

src/main/resources/oracle-to-postgres-javarules.json
src/main/resources/oracle-to-postgres-mvnrules.json
src/main/resources/oracle-to-postgres-properties.json
src/main/resources/oracle-to-postgres-recommendations.json
src/main/resources/oracle-to-postgres-xmlrules.json

Updated recommendation numbers to be unique across use cases

Updated recommendation numbers to be unique across usecases

---

src/main/resources/weblogic-to-wildfly-javarules.json
src/main/resources/weblogic-to-wildfly-recommendations.json

Rules for Authentication and JNDI syntax for weblogic to wildfly migration

---

README.md
src/main/resources/weblogic-to-wildfly-javarules.json
src/main/resources/weblogic-to-wildfly-recommendations.json

weblogic to wildfly java recommendations v1

---

src/main/java/com/amazon/aws/am2/appmig/estimate/xml/XMLFileAnalyzer.java
src/main/resources/weblogic-to-wildfly-recommendations.json
src/main/resources/weblogic-to-wildfly-xml.json

xml only tag name check support, weblogic to wildfly xml rules

---

src/main/java/com/amazon/aws/am2/appmig/estimate/properties/PropertyFileAnalyzer.java
src/main/resources/weblogic-to-wildfly-properties.json
src/main/resources/weblogic-to-wildfly-recommendations.json

1. fn to check prop name By wildcard match, 2. wildfly property rules

---

src/main/java/com/amazon/aws/am2/appmig/constants/IConstants.java
src/main/java/com/amazon/aws/am2/appmig/estimate/Estimator.java
src/main/java/com/amazon/aws/am2/appmig/estimate/Plan.java
src/main/java/com/amazon/aws/am2/appmig/estimate/Recommendation.java
src/main/java/com/amazon/aws/am2/appmig/estimate/properties/PropertyFileAnalyzer.java
src/main/java/com/amazon/aws/am2/appmig/estimate/xml/XMLFileAnalyzer.java
src/main/java/com/amazon/aws/am2/appmig/glassviewer/JavaGlassViewer.java
src/main/java/com/amazon/aws/am2/appmig/utils/Utility.java
src/main/resources/ibmmq-to-amazonmq-javarules.json
src/main/resources/oracle-to-postgres-javarules.json
src/main/resources/oracle-to-postgres-mvnrules.json
src/main/resources/oracle-to-postgres-properties.json
src/main/resources/oracle-to-postgres-xmlrules.json
src/main/resources/reporttemplate.html
src/main/resources/sqlreporttemplate.html
src/main/resources/weblogic-to-tomcat-javarules.json
src/main/resources/weblogic-to-tomcat-mf.json
src/main/resources/weblogic-to-tomcat-mvnrules.json
src/main/resources/weblogic-to-tomcat-properties.json
src/main/resources/weblogic-to-tomcat-xml.json
src/main/resources/weblogic-to-wildfly-javarules.json
src/main/resources/weblogic-to-wildfly-mvnrules.json
src/main/resources/weblogic-to-wildfly-properties.json
src/main/resources/weblogic-to-wildfly-xml.json

Streamlines the effort estimations

streamlined the effort estimations
